version: '3.3'
services:
  db:
    image: mysql:5.7
    env_file:
        - database.env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - zup-mysql:/var/lib/mysql
        #  stock-quota-manager:
        #build: .
        #depends_on:
        #- db
        #ports:
        #- '8081:8081'
        #expose:
        #- '8081'

volumes:
    zup-mysql:
