version: '3.3'
services:
  db:
    image: postgres
    env_file:
        - database.env
    ports:
      - '5432:5432'
    expose:
      - '3306'
    volumes:
      - zup-postgres:/var/lib/postgresql/data

volumes:
    zup-postgres:
